Adds tracing subscriber layer for JSON -> Workers
cloudflare/daphne pull request #308
Opened 2023-04-24 13:29 UTC by will118

With this change, logging under `DAP_DEPLOYMENT=prod` will flatten fields from spans into the log line, allowing us to add fields like `correlation_id` which can be helpful when debugging.

This commit also moves `tracing_utils.rs` to a new directory.

2023-04-24 13:39 UTC, bhalleycf approved these changes

2023-04-24 16:43 UTC, cjpatton requested changes
Looks good to me! One blocking comment: The new file needs a copyright notice.

2023-04-24 16:43 UTC, cjpatton commented on daphne_worker/src/tracing_utils/workers_json_layer.rs
This file needs a copyright notice.

2023-04-24 16:49 UTC, cjpatton approved these changes

2023-04-25 18:10 UTC, xtuc approved these changes

2023-04-25 18:11 UTC, merged