Split DaphneWorkerConfig into DaphneWorkerConfig and DaphneWorkerDoConfig
cloudflare/daphne pull request #465
Opened 2023-12-20 11:47 UTC by mendess

To run exclusively DOs we don't need to load all the configuration values needed for a full worker. As such we split these two in order to make configuring the storage proxy worker simpler.

2023-12-20 23:44 UTC, cjpatton requested changes
This is an improvement over all, but it creates a new problem: we now mingle secrets with non-secret configuration parameters in the same configuration file, configuration.toml. (Previously this was not an issue because Workers treats both as environment variables.)

That said, I appreciate if this is intended as an incremental step and you'd like to address this problem later.

2023-12-20 23:44 UTC, cjpatton commented on daphne_server/examples/configuration.toml
> +report_shard_key = "2e0a99e5a047510243e08289811db0386c620644ae53bafdd50604678f3ec537"
```suggestion
report_shard_key = "2e0a99e5a047510243e08289811db0386c620644ae53bafdd50604678f3ec537" # SECRET
```

2023-12-20 23:44 UTC, cjpatton commented on daphne_server/examples/configuration.toml
(Initially discussed in #460.) In a real deployment we'll need to be able to make changes to this file without having to touch secrets. What is our plan for this?

For daphne_worker the story is pretty simple: For testing we can leave the "secrets" in wrangler.toml; in the deployed code, we set the secret with `wrangler secret`. This was possible because the Worker treats them like environment variables either way. It doesn't seem like this could work this same way.

I'm not sure how the new service infra works, but if this were a standard edge service, we would do one of two things:
1. Store each secret in a file and load them either here (with some toml magic) or on startup.
2. At startup, request the keys from some key management service, like Quicksilver.

I'm not sure we should land this code until we've figured this out.

2023-12-20 23:44 UTC, cjpatton commented on daphne_server/examples/configuration.toml
> +leader_auth.bearer_token = "I am the leader!" # SECRET
If feasible, I'd suggest using values here that look more like bearer tokens. I believe [something like](https://swagger.io/docs/specification/authentication/bearer-authentication/)
```
Bearer <randdom 16 byte hex string>
```

2023-12-20 23:44 UTC, cjpatton commented on daphne_service_utils/src/config.rs
> +/// Daphne-Worker configuration, including long-lived parameters used across DAP tasks.
Perhaps we want a generic term that applies to either daphne_worker or daphne_server
```suggestion
/// Daphne server configuration, including long-lived parameters used across DAP tasks.
```

2023-12-20 23:44 UTC, cjpatton commented on daphne_worker/src/durable/reports_pending.rs
> +    config::DaphneWorkerDoConfig,
Consistency
```suggestion
    config::DaphneWorkerDurableConfig,
```

2023-12-21 20:48 UTC, cjpatton reviewed
I've resolved a couple of comments based on our discussion today.

2023-12-21 20:48 UTC, cjpatton commented on daphne_server/examples/configuration.toml
Update: @mendess clarified that this config mechanism is for the example only -- in the real deployment we'll have to use Vault any way, which means something like this won't be an option.

2023-12-21 20:48 UTC, cjpatton commented on daphne_server/examples/configuration.toml
> +leader_auth.bearer_token = "I am the leader!" # SECRET
Ignore this since it would break the end to end tests

2023-12-21 23:22 UTC, mendess commented
> This is an improvement over all, but it creates a new problem: we now mingle secrets with non-secret configuration parameters in the same configuration file, configuration.toml. (Previously this was not an issue because Workers treats both as environment variables.)
> 
> That said, I appreciate if this is intended as an incremental step and you'd like to address this problem later.

This configuration file is just an example, all of the values that are present in it can be passed through environment variables as well. For example, the `report_shard_key` can be provided through the `DAP_SERVICE_REPORT_SHARD_KEY` environment variable in a production setting. Either way the `examples/service.rs` is just for e2e testing and is not meant to mimic a real production server

2023-12-21 23:39 UTC, cjpatton approved these changes

2023-12-22 00:10 UTC, merged