Add Dockerfile.interop_helper
cloudflare/daphne pull request #545
Opened 2024-03-18 21:12 UTC by cjpatton

Add a Dockerfile for driving interop tests against our Helper according to draft-dcook-ppm-dap-interop-test-design-07. To run it:

```
docker build . -f Dockerfile.interop_helper --tag daphne_interop
docker run -it -p 8788:8788 -P daphne_interop
```

To verify it is running:

```
curl http://localhost:8788/internal/test/ready -X POST
```

Also, don't install `worker-build` from `worker` in order to make `worker dev` start up faster.

2024-03-19 16:12 UTC, mendess requested changes

2024-03-20 17:22 UTC, mendess requested changes
Create a `docker-interop` dir in the root to house the 2 new files, just so the root of the repo is cleaner

2024-03-21 22:43 UTC, cjpatton commented
TODO: Split logs into files: https://ietf.slack.com/archives/C02P9620XT6/p1710868689386369?thread_ts=1710868077.859259&cid=C02P9620XT6

2024-04-11 23:58 UTC, cjpatton commented on run_interop_helper.sh
> +env RUST_LOG=info /build/target/release/examples/service -c /build/daphne_server/examples/configuration-helper.toml | ansi2txt &
I was trying to be "docker efficient" by building the service at a lower layer than the script.

2024-04-12 15:14 UTC, cjpatton commented
> Create a `docker-interop` dir in the root to house the 2 new files, just so the root of the repo is cleaner

I tried this initially and couldn't get it to work. It seems like docker wants the Dockerfile to be in the working directory where you are copying files into it. Can you give this a try?

2024-04-15 21:06 UTC, merged