Add support for public extensions in Reports.
cloudflare/daphne pull request #754
Opened 2024-12-31 15:38 UTC by jhoyla

Draft 13 adds mandatory support for public extensions in the ReportMetadata, but doesn't define any (Taskprov is (for now) a private extension). This PR adds support for rejecting unknown extensions, which is all of them.

2025-01-01 16:00 UTC, cjpatton reviewed
I believe we're missing one feature: we need to resolve repeated extensions across the public and private extension fields.

2025-01-02 13:05 UTC, jhoyla commented
> I believe we're missing one feature: we need to resolve repeated extensions across the public and private extension fields.

So the spec says:
```textCheck if any two public or private report extensions have the same extension
type. (For the purposes of this check, a private report extension can conflict
with a public report extension.) If so, the Aggregator MUST mark the input share
as invalid with error invalid_message.
```
Which I take to mean a conflict between the public and private extensions is allowed.
We also don't have any public extensions defined, presumably the text in https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap-taskprov/pull/98 will only be included in draft-14?

2025-01-02 13:43 UTC, mendess reviewed
not even a nit, just a comment. I don't have a preference but instead of `Vec::new()` you can write `vec![]`

2025-01-02 16:40 UTC, cjpatton commented
> > I believe we're missing one feature: we need to resolve repeated extensions across the public and private extension fields.
> 
> So the spec says:
> 
> ```
> type. (For the purposes of this check, a private report extension can conflict
> with a public report extension.) If so, the Aggregator MUST mark the input share
> as invalid with error invalid_message.
> ```
> 
> Which I take to mean a conflict between the public and private extensions is allowed. If I add support for taskprov as a public extension do I reject it if it appears in both places?

The intent of the text is: "if the same extension appears twice, then the report MUST be rejected - regardless of what fields the extensions appear in." In particular, if the taskprov extension appears in the public and private fields, then reject.

2025-01-08 15:04 UTC, mendess approved these changes

2025-01-10 00:16 UTC, cjpatton requested changes
The code looks largely correct, though I have some suggestions for behavior changes. I think the tests need a bit of work. Also, I have some suggestions for making the code a little cleaner/easier to read.

2025-01-10 00:16 UTC, cjpatton commented on crates/daphne/src/protocol/mod.rs
> +    test_versions! {handle_unknown_public_extensions_in_report}
Note: This creates the test for all versions of DAP, including draft 09.

2025-01-10 00:16 UTC, cjpatton commented on crates/daphne/src/roles/leader/mod.rs
> +            if crate::protocol::no_duplicates(extensions.iter()).is_err() {
And `use crate::protocol;`. Also, we should rename `no_duplicates` to something more distinctive.

```suggestion
            if protocol::no_duplicates(extensions.iter()).is_err() {
```

2025-01-10 00:16 UTC, cjpatton commented on crates/daphne/src/roles/leader/mod.rs
Add a comment here telling the reader what's going on.

2025-01-10 00:16 UTC, cjpatton commented on crates/daphne/src/roles/leader/mod.rs
> +        }
I'm not sure either of these arms could ever be reached, assuming the code that sets `public_extensions` is correct. If I were you, I would use the `public_extension.is_some()` to deduce which version was negotiated. Tnen we could replace this big ugly `match` with:

```rust
if let Some(public_extensions) = &report.report_metadata.public_extensions {
    ...  // check for duplicates, unorecgonized values, and so on
}
```

2025-01-10 00:16 UTC, cjpatton commented on crates/daphne-server/tests/e2e/e2e.rs
> +async fn leader_collect_taskprov_repeated_abort() {
What does this new test do?

2025-01-10 11:17 UTC, mendess commented on crates/daphne/src/error/aborts.rs
> +        let detail = serde_json::to_string(&unknown_extensions);
Why use json here? We don't expect anyone to parse the detail, you could just use
```suggestion
        let detail = format!("{unknown_extensions:?}");
```
which I think will output exactly the same thing in this case

2025-01-14 14:35 UTC, jhoyla commented on crates/daphne-server/tests/e2e/e2e.rs
> +async fn leader_collect_taskprov_repeated_abort() {
It checks that the Leader aborts if the `taskprov` extension appears in both the public and private extensions.

2025-01-14 14:45 UTC, jhoyla commented on crates/daphne-server/tests/e2e/e2e.rs
> +async fn leader_collect_taskprov_repeated_abort() {
I fixed a bug in it too.

2025-01-14 15:46 UTC, cjpatton reviewed
Looks pretty good. Let's chat in our 1:1 about the necessity of the e2e tests.

2025-01-14 15:46 UTC, cjpatton commented on crates/daphne-server/tests/e2e/e2e.rs
> +#[tokio::test]
Can we move these tests to the `daphne` crate?

2025-01-14 15:46 UTC, cjpatton commented on crates/daphne-server/tests/e2e/e2e.rs
> +async fn leader_collect_taskprov_repeated_abort() {
Can we move this to the unit tests in the `daphne` crate. or does exercise a behavior that's not implemented by `InMemoryAggregator`?

2025-01-14 15:46 UTC, cjpatton commented on crates/daphne/src/messages/mod.rs
> +            _ => return Err(CodecError::UnexpectedValue),
We usually use this for encoding. How about his:
```suggestion
            _ => return Err(CodecError::Other("encountered incorrectly set public extensions".into()))s
```

2025-01-14 15:46 UTC, cjpatton commented on crates/daphne/src/protocol/client.rs
> +                ))
I would actually go with a fatal error here
```suggestion
                return Err(fatal_error!(
                    err = format!("public extensions not set correctly for {version:?}")
                ));
```

2025-01-14 15:46 UTC, cjpatton commented on crates/daphne/src/protocol/client.rs
> +            _ => (),
nit: you can avoid having to specify this arm using `if let`:F

```rust
if let (Some(_), DapVersion::Draft09) | (None, DapVersion::Latest) =
            (&public_extensions, version)
{
    ...
}

```

2025-01-14 15:46 UTC, cjpatton commented on crates/daphne/src/roles/leader/mod.rs
> +        // the decoding / error checking happens in the extractor).
```suggestion
        // the decoding / error checking happens in the extractor.
```

2025-01-14 15:46 UTC, cjpatton commented on crates/daphne/src/roles/leader/mod.rs
> +        };
IF the metdata "well-formed" (see above comment), then do we need to check for repeats here?

2025-01-14 16:40 UTC, cjpatton commented on crates/daphne-server/tests/e2e/e2e.rs
> +    report.report_metadata.public_extensions = Some(vec![Extension::Taskprov, Extension::Taskprov]);
Overwriting exetensions causes an HPKE decryption failure, which isn't what we intend to test here. Modify `produce_report()` to take in public extensions and set them as you've set them here.

2025-01-14 16:40 UTC, cjpatton commented on crates/daphne-server/tests/e2e/e2e.rs
> +    ]);
Same thing here: don't override

2025-01-14 16:40 UTC, cjpatton commented on crates/daphne-server/tests/e2e/e2e.rs
> +async fn leader_upload_taskprov_public() {
Remove this test (already covered by unit tests).

2025-01-14 16:42 UTC, cjpatton commented on crates/daphne-server/tests/e2e/e2e.rs
> +async fn leader_collect_taskprov_repeated_abort() {
Make sure there's a unit test for this and delete.

2025-01-14 16:43 UTC, cjpatton commented on crates/daphne/src/roles/mod.rs
> +        }]);
Don't override, as this causes hpke decryption to fail. Here and below.

2025-01-15 12:49 UTC, jhoyla commented on crates/daphne/src/roles/leader/mod.rs
> +        };
Well formed in the sense that if the version is `DapVersion::Latest` then `public_extensions.is_some()`, and that if the version is `DapVersion::Draft09` then `public_extensions.is_none()`. It doesn't say the data is good, just that it's correctly formed.

2025-01-15 13:09 UTC, jhoyla commented on crates/daphne/src/roles/mod.rs
> +        }]);
I'm leaving the one below in place. The test below checks that a malformed report is appropriately handled. Generating the malformed report with the correct HPKE data would require a lot more code, and given that in this test the HPKE data is never checked this is much less brittle.

2025-01-15 15:49 UTC, cjpatton approved these changes

2025-01-16 17:57 UTC, cjpatton commented
I've rebased this PR and updated the capnp schema to include the public extensions field. I've also added unit tests to confirm encoding/decoding works (thanks @mendess for the help there).

2025-01-16 18:00 UTC, cjpatton commented
Updated the commit to fix clippy

2025-01-16 18:05 UTC, cjpatton commented on crates/daphne-service-utils/src/compute_offload/compute_offload.capnp
> +struct PublicExtensionsList @0x8b3c98c0ddd0043e {
@mendess I just ran `capnp id` and pasted the output here. So this is really just a random ID that needs to be unique?

2025-01-16 18:06 UTC, mendess approved these changes
looks good to me

2025-01-16 18:19 UTC, cjpatton commented
Rebased on the PR @mendess merged, hoping that solves the `cargo doc` failure.

2025-01-16 18:47 UTC, merged