Fix & shrink Miniflare-baed test container.
cloudflare/daphne pull request #96
Opened 2022-08-23 16:33 UTC by branlwyd

This container had stopped building successfully (I think the Daphne
codebase started using a Rust feature that wasn't stabilized until after
1.61; bumping to 1.63 was all that was needed to get a successful
build.)

While I was at it, I also split the container build into a "build"
portion and an "output" portion & switched to alpine-based base images
-- this shrunk the output image from 3.32GB to 390MB.

Also go back to building Daphne using the mainline version of workers-rs,
as the referenced issue has been fixed.

2022-08-23 16:35 UTC, branlwyd commented
(Context: Janus currently tests w/ a precompiled version of Daphne, which among other issues will quickly skew badly out of date. Unless/until a public container is published, I'm hoping to dynamically build a container image for testing. I was able to feed the container built by this dockerfile into our test framework & it passed, so I'm moderately confident that this container works.)

2022-08-23 20:20 UTC, cjpatton requested changes
Changes to the `miniflare` container look good! To get the end-to-end tests running via docker-compose, we also need to change `runtests` to use rust 1.63. Would you mind making this change here?

2022-08-23 22:01 UTC, branlwyd commented
OK, done -- the `docker-compose` invocation you mention now succeeds. I had to make a few other minor changes to get things running, mentioned in the commit description.

Other than what's mentioned in the commit description, I also:
* Only run the `daphne_worker_test` tests, to approximate only running the E2E tests. I suppose it's not so useful to run unit-tests that would be run by a normal `cargo test` in this case.
* Update the Dockerfile's `cargo` invocation to build with the same profile/features as the real `cargo test` that is run by `test.sh`. This avoids the `test.sh` invocation from having to build things -- all of the Rust compilation happens at `docker build` time now.

I didn't minimize the `runtests` docker image, as it's basically an ephemeral image to drive a test.

2022-08-24 18:10 UTC, cjpatton approved these changes
Thanks @branlwyd! I haven't gotten the end-to-end tests to run via docker-compose yet, but since this PR isn't a regression and it unblocks you, I will merge it now and address the issue later (hopefully today).

2022-08-24 18:10 UTC, merged